service: miranda-backend

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs20.x
  environment:
    TOKEN_SECRET: ${env:TOKEN_SECRET}
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origins:
              - ${env:DOMAIN_FRONT} 
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origins:
              - ${env:DOMAIN_FRONT}
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true

  login:
    handler: dist/controllers/auth.loginController
    events:
      - http:
          path: /login
          method: POST
          cors:
            origins:
              - ${env:DOMAIN_FRONT}
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true

  optionsLogin:
    handler: dist/controllers/auth.optionsHandler
    events:
      - http:
          path: /login
          method: OPTIONS
          cors:
            origins:
              - ${env:DOMAIN_FRONT}
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
