service: miranda-backend

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs20.x
  environment:
    TOKEN_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlZ3dhbmRhMTJAZ21haWwuY29tIiwiaWF0IjoxNzI3MzQ2NzY4fQ.P1QSO2vpmFf3F3EyF7W6Yzt1VJYNVkI2wmaFoB-Vd_4
    MONGODB_URI: mongodb+srv://segwanda12:miranda@miranda.jwtaj.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    DOMAIN_FRONT: http://dashboard-miranda-mgl.s3-website.eu-west-3.amazonaws.com/

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"

plugins:
  - serverless-dotenv-plugin
