name: Deploy Miranda Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js (Required for Serverless Framework)
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Serverless Framework v3
        run: npm install -g serverless@3

      - name: Install dependencies
        run: |
          npm install
          npm install mysql2

      - name: Build Vite App
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up environment variables
        run: |
          echo "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" >> $GITHUB_ENV
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

      - name: Remove CloudFormation Stack if it exists
        run: serverless remove --stage dev || echo "Stack not found or already removed"

      # Paso de despliegue
      - name: Deploy with Serverless v3
        run: serverless deploy
